name: Popcorn JS e2e tests

on:
  push:
    branches: ["**"]
    paths:
      - "js/popcorn/**"
      - "lib/**/wasm.ex"
      - ".github/workflows/popcorn_js_e2e_test.yml"

permissions:
  contents: read

env:
  CI: true

jobs:
  e2e:
    name: JS E2E tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.7

      - name: Set up Elixir
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
        with:
          elixir-version: "1.17.3"
          otp-version: "26.0.2"
          rebar3-version: "3.18.0"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: js/pnpm-lock.yaml

      - name: Install AtomVM build deps
        run: |
          sudo apt-get update && sudo apt-get install -y gperf libmbedtls-dev zlib1g-dev

      - name: Restore Elixir dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install Elixir dependencies
        run: mix deps.get

      - name: Install JS dependencies
        run: pnpm install
        working-directory: js

      - name: Build popcorn JS package
        run: pnpm build:prod
        working-directory: js/popcorn

      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium --with-deps
        working-directory: js/popcorn

      - name: Run e2e tests
        run: pnpm test:e2e
        working-directory: js/popcorn
